logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
server:
  port: ${SERVER_PORT}
  error:
    include-exception: true
mail:
  host: sandbox.smtp.mailtrap.io
  port: 2525
  ssl: no
  tls: yes
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
app:
  default:
    password: test123
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/dotodo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=EET
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    packages-to-scan:
      - com.pago.dotodo.model.entity
    generate-ddl: true
  mvc:
    hidden-method:
      filter:
        enabled: true
cloudinady:
  api-key: ${IMG_UPL_API_KEY}
  api-secret: ${IMG_UPL_API_SECRET}
  cloud-name: ${IMG_UPL_API_NAME}